### PR TITLE
added missing devices

### PR DESCRIPTION
**Pull request by dougberkland**

### CODE REVIEW

**Review by dougberkland — COMMENTED** [review]
The changes to DevCat might not be required as it appears that the inner interfaces of the class might be completely unused.

**Comment by kuniss** [comment]
Thanks for the contribution, @dougberkland !
It is very welcome.

Well done! No complains from my side. :smile: 
I will try to build and publish it next week.

**Comment by kuniss** [comment]
> The changes to DevCat might not be required as it appears that the inner interfaces of the class might be completely unused.

I guess, this are more like marker interfaces. We do use them quite rarely. There have been designed before my time, so I'm cannot really assess, how important they are.
Nevertheless, good to have it completed now.

**Comment by kuniss** [comment]
@dougberkland, just one note: When I contributed to upstream repositories from my fork's master, it was a nightmare to get it in sync afterwards again with the upstream master after the PR had been merged on upstream. It shows up as the "this branch is x commits behind and y commits ahead of upstream/master" problem...

After that, I read in some articles that it is far better (save efforts and headaches) to open a branch at your fork and create a pull request from that branch. Afterwards, when the PR has been merged to the upstream master/main branch it is quite easy to get in sync again on your forks master/main with the upstream (Just by pressing the button on the GitHub GUI for syncing).

Your branch from which the PR has been made can than just be closed and forgotten (in your fork repo; it will be living forever in the PR).  

Do you want to redo the PR in that way?

But I guess, your master branch is now already half in the problem. So you will have to do a hard git reset either. 
Please inform me how do you want to proceed. I just wanna save your time... for me it is only a click, anyway.

**Comment by dougberkland** [comment]
Thank you for the advice for future PRs. For this one, I will clean up my
fork.

**Comment by kuniss** [comment]
@dougberkland , unfortunately I did not find time to push your contribution to a release.
Hopefully, this will take place in the week of November 11th.
I was nearly ready, but on the last turn a Github Action issue came up, I need to resolve first.

**Comment by kuniss** [comment]
@dougberkland It's released as [javapos-config-loader-3.1.0](https://oss.sonatype.org/service/local/repositories/releases/content/org/javapos/javapos-config-loader/3.1.0/javapos-config-loader-3.1.0.jar). :tada:

**Pull request merged**
