### PR TITLE
Update jcl.dtd

### PR DESCRIPTION
**Pull request by mjpcger**
This is the updated file, see issue 3. Hope I made it right. Didn't use gitpod, but GitHub Desktop, the GitHub web UI and an editor instead.

### CODE REVIEW

**Comment by mjpcger** [comment]
Solves issue 3

**Comment by kuniss** [comment]
Looks good!
I will check it in the next days, hopefully. I'm currently a bit overloaded with project at the company...

**Comment by kuniss** [comment]
... Should be 36 device categories. I'm counting less, 26 only.
Did you miss some, e.g. RFIDScanner?

We should have all 36 incorporated!

**Comment by mjpcger** [comment]
Made further commits. Don't know how the changes could be corrupted previously. Now there **are** 36 classes (in fix-issue-2 branch).

**Review by kuniss — APPROVED** [review]
Well done.

**Comment by kuniss** [comment]
However, you have to wait a little bit more until this fix gets part of an release as issue #5 has to be solved first.

**Pull request merged**
